### PR TITLE
Update CI

### PR DESCRIPTION
**Pull request by kigawas**
related with #83 

make tests pass on nightly (for now) via Travis
&
make builds pass on stable, beta and nightly via Github Action

### CODE REVIEW

**Comment by kigawas** [comment]
https://github.com/SergioBenitez/Rocket/issues/19

once this done, we can try to make it build on stable, beta and nightly

**Comment by amanusk** [comment]
Is it possible to run all tests on travis and not split the tests between travis and github -ci?

**Comment by kigawas** [comment]
> Is it possible to run all tests on travis and not split the tests between travis and github -ci?

you can, but what we want is to check whether it can __build__ on stable, beta (and nightly) since rocket can only run on nightly
once rocket can build on stable, this can be removed easily and use travis to run tests (or you can remove travis)

**Comment by kigawas** [comment]
or you can rewrite examples to remove rocket
pity that there's no "example-only dependency" in rust for now

**Comment by amanusk** [comment]
Although a bit of an overkill, we can do this for travis:
```yaml
language: rust

before_script:
  - rustup component add rustfmt-preview
  - cargo fmt --all -- --check

matrix:
  include:
    - os: osx
      rust: stable
      script:
        - cargo build

    - os: osx
      rust: beta
      script:
        - cargo build

    - os: osx
      rust: nightly
      script:
        - cargo build
        - cargo test --verbose

    - os: linux
      rust: stable
      script:
        - cargo build

    - os: linux
      rust: beta
      script:
        - cargo build

    - os: linux
      rust: nightly
      script:
        - cargo build
        - cargo test --verbose
```
Tests only run on nightly and no need to add another ci tool (for now)

**Pull request merged**
