### PR TITLE
Python bindings

### PR DESCRIPTION
**Pull request by ysangkok**
Please let me know if there are any issues with this. Some code is commented out because I found that an unwrap would crash everything. I presume these issues are known. I didn't add deserialization support for all objects since I don't think they'll be sent over the wire. The code is very repetitive, I don't know what your policy regarding macros is.

### CODE REVIEW

**Comment by ysangkok** [comment]
For example, if I swap the first two arguments for `verify_commitments_and_dlog_proof`, relevant frames:

```
   5: std::panicking::begin_panic
             at libstd/panicking.rs:410
   6: multi_party_ecdsa::protocols::two_party_ecdsa::lindell_2017::party_two::KeyGenSecondMsg::verify_commitments_and_dlog_proof
             at src/protocols/two_party_ecdsa/lindell_2017/party_two.rs:110
   7: p2_keygen2_nullable_new_verify_commitments_and_dlog_proof
             at src/c_interface.rs:203
```

The line is an `assert!`.

The other crash is:

```
panicked at 'called `Result::unwrap()` on an `Err` value: InvalidPublicKey', libcore/result.rs:1009:5

  10: <cryptography_utils::elliptic::curves::secp256_k1::Secp256k1Point as cryptography_utils::elliptic::curves::traits::ECPoint<secp256k1::key::PublicKey, secp256k1::key::SecretKey>>::from_coor
             at /home/janus/.cargo/git/checkouts/cryptography-utils-be6ae967a696283d/4d7554f/src/elliptic/curves/secp256_k1.rs:297
  11: <cryptography_utils::elliptic::curves::secp256_k1::Secp256k1PointVisitor as serde::de::Visitor<'de>>::visit_map
             at /home/janus/.cargo/git/checkouts/cryptography-utils-be6ae967a696283d/4d7554f/src/elliptic/curves/secp256_k1.rs:369
  12: <&'a mut serde_json::de::Deserializer<R> as serde::de::Deserializer<'de>>::deserialize_map
             at /home/janus/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.32/src/de.rs:1493
  13: <cryptography_utils::elliptic::curves::secp256_k1::Secp256k1Point as serde::de::Deserialize<'de>>::deserialize
             at /home/janus/.cargo/git/checkouts/cryptography-utils-be6ae967a696283d/4d7554f/src/elliptic/curves/secp256_k1.rs:340
  14: <core::marker::PhantomData<T> as serde::de::DeserializeSeed<'de>>::deserialize
             at /home/janus/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.79/src/de/mod.rs:778
  15: <serde_json::de::MapAccess<'a, R> as serde::de::MapAccess<'de>>::next_value_seed
             at /home/janus/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.32/src/de.rs:1730
  16: serde::de::MapAccess::next_value
             at /home/janus/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.79/src/de/mod.rs:1839
  17: <cryptography_utils::cryptographic_primitives::proofs::dlog_zk_protocol::_IMPL_DESERIALIZE_FOR_DLogProof::<impl serde::de::Deserialize<'de> for cryptography_utils::cryptographic_primitives::proofs::dlog_zk_protocol::DLogProof>::deserialize::__Visitor<'de> as serde::de::Visitor<'de>>::visit_map
             at /home/janus/.cargo/git/checkouts/cryptography-utils-be6ae967a696283d/4d7554f/src/cryptographic_primitives/proofs/dlog_zk_protocol.rs:43
  18: <&'a mut serde_json::de::Deserializer<R> as serde::de::Deserializer<'de>>::deserialize_struct
             at /home/janus/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.32/src/de.rs:1551
  19: cryptography_utils::cryptographic_primitives::proofs::dlog_zk_protocol::_IMPL_DESERIALIZE_FOR_DLogProof::<impl serde::de::Deserialize<'de> for cryptography_utils::cryptographic_primitives::proofs::dlog_zk_protocol::DLogProof>::deserialize
             at /home/janus/.cargo/git/checkouts/cryptography-utils-be6ae967a696283d/4d7554f/src/cryptographic_primitives/proofs/dlog_zk_protocol.rs:43
  20: serde_json::de::from_trait
             at /home/janus/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.32/src/de.rs:2115
  21: serde_json::de::from_str
             at /home/janus/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.32/src/de.rs:2260
  22: d_log_proof_nullable_new_deserialize
             at src/c_interface.rs:84
```

The crashing code is in `mpecdsa.py`.

**Comment by omershlo** [comment]
For the first `assert!` crash - why do you want to swap the first two arguments ? Anyway this is good point - we need to deal with this error case more gracefully. cc: @gbenattar .  

About the second error - We fixed it already.  There are a few restrictions that the underlying lib-secp256k1 is enforcing to allow to create public key from a slice.  In `Cargo.toml` you need to remove: 
` tag = "v0.0.1"` from the cryptography-utils dependency. Let me know if this not solve it.  @gbenattar can this crash happens for the wallet as well? 

@gbenattar / @tzachvk  you are probably in best position to explain what should be sent over the wire and currently missing deserialization ? 

@ysangkok - the observation about repetition is accurate. I think that Macros are very much needed. 
As a general note: the most updated code is in branch `pdl-sub-protocol`, and we now working on pushing those changes to `master`. I suggest to open an issue to update the python binding to this new version.

**Comment by gbenattar** [comment]
_Side comment: @ysangkok Maybe you should give a quick look to KMS (https://github.com/KZen-networks/kms)? this is where we implemented our bindings for Node.js / Typescript._

What is the motivation behind this PR? Experimental benchmarking? I would be in favor of "enabling" the _c_interface_ module as a non default feature. Also, a unit test would be necessary.

Also we have this common problem of writing interop interfaces (Rust <> Node, Rust <> C <> Python, Rust <> C <> Swift). I am wondering if it can be worth it to look into https://github.com/eqrion/cbindgen.

About ser/de what is you goal? Do you also want to benchmark 2P-ECDSA with networking? If yes, I suggest we set up some time to discuss it, we did this work already (not in Python, not open-source) and it is important for us to evaluate the need for the community, we might share more.

**Comment by gbenattar** [comment]
This PR has not activity since a year, I am closing it. Feel free to re-open if relevant.

**Pull request closed without merging**
